### ISSUE TITLE
Is there a way to enable/disable ?

### ISSUE THREAD

**Issue by jrobles-boom** [mir3z/texthighlighter#10]
Hi,
Is there a way to toggle hilighting events? to make a button On/Off (or select/deselect a color) the behavior.
Thanks

**Comment by mir3z** [comment]
Currently the only way is to use destroy() method, but later you will have to create a new highlighter to re-enabled highlighting.
I wil add enabling/disabling functionality in a spare time.

**Comment by nickam992** [comment]
Hey mir3z, any update on making an On/Off button?  Also, how do you call the destroy method correctly?  I'm able to call it, but the event listener doesn't actually get removed.  
Here's how I'm creating the highlighter:
this.highlighter = new TextHighlighter( $("#container")[0] );

And here's how I'm attempting to destroy it:
this.highlighter.destroy();
