### ISSUE TITLE
Is there a way to remove a highlight from a selection instead a whole element?

### ISSUE THREAD

**Issue by jrobles-boom** [mir3z/texthighlighter#11]
I'm trying to unmark a single selection but removeHighlights removes all the highlights.

**Comment by mir3z** [comment]
There is no such functionality right now. You can only remove highlight(s) from a given element (http://mir3z.github.io/texthighlighter/doc/TextHighlighter.html#removeHighlights).
However, you are more than welcome to implement this by yourself and then request a pull.

**Comment by vinniejames** [comment]
This took me a while to figure out as well, since I was trying to use `.click()`, which doesn't add listeners to nodes that don't exist yet.

The solution was to use [`.on()` instead]( https://stackoverflow.com/questions/15092578/on-vs-live-click-function-on-element-that-doesnt-exist-yet):

```
$(document.body).on('click','.highlighted', function(e){
	hltr.removeHighlights(e.target);
});
```
