### ISSUE TITLE
Feature request: remove a single highlight

### ISSUE THREAD

**Issue by justusromijn** [mir3z/texthighlighter#14]
Is it possible to extend the API to support removing a single highlight? If I remove a highlight in an element with multiple highlights, it does not work properly because the paths are no longer correct.

**Comment by mir3z** [comment]
Let's clarify: you need a way to remove highlight from a single element but to keep highlights for its children?

**Comment by justusromijn** [comment]
I think this issue no longer stands, we found a way around the issue.
