### ISSUE TITLE
dynamically add highlights

### ISSUE THREAD

**Issue by vsoch** [mir3z/texthighlighter#32]
hey @mir3z ! This is a really great util! I have a question that (I hope) is pretty straight forward. I have an application where I am saving user highlights by serializing. When they come back to the page, I want the (old) highlights to load automatically. I also have a collaborative function that has users working together, and I am able to send the serialized highlights from one browser to the other in real time. What function do I hand (any highlight / range) to in order for the highlight to show up colored on the screen? Many thanks!

**Comment by ali-h2010** [comment]
You just need to deserialize the serialized json which contains all what the deserializer needs such as the number of highlights, location, and range.

just check the serialization example.
 - select some text to serialize
 - click serialize, the highlights will be removed and you will get the serialized output in the console
 - click deserialize to get the serialized output and highlight the text.

**Comment by vsoch** [comment]
hey @ali-h2010 I fixed this up more than 6 months ago, so I'm ok to close the issue. Thanks!
